repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.0
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
        always_run: true
        stages: [pre-commit]
      # Run the formatter.
      - id: ruff-format
        always_run: true
        stages: [pre-commit]
    