repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.15
    hooks:
      # Update the uv lockfile
      - id: uv-lock
        always_run: true
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.0
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
        always_run: true
      # Run the formatter.
      - id: ruff-format
        always_run: true