services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:latest
    env_file: .env
    healthcheck:
      test: ["CMD", "pg_isready","-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local